services:
  db:
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress_01
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - db:/var/lib/mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    networks:
      - sites
    secrets:
      - db_root_password

  wordpress_01:
    extends:
      file: ./common-services.yml
      service: wordpress
    environment:
      WORDPRESS_DB_NAME: wordpress_01
    volumes:
      - wordpress_01:/var/www/html
      - ./wordpress/php/wordpress_01.ini:/usr/local/etc/php/conf.d/wordpress_01.ini

  # wordpress_02:
  #   extends:
  #     file: ./common-services.yml
  #     service: wordpress
  #   environment:
  #     WORDPRESS_DB_NAME: wordpress_02
  #   volumes:
  #     - wordpress_02:/var/www/html
  #     - ./wordpress/php/wordpress_02.ini:/usr/local/etc/php/conf.d/wordpress_02.ini

  nginx:
    depends_on:
      - wordpress_01
      # - wordpress_02
    restart: unless-stopped
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx/conf.d/wordpress_01.conf:/etc/nginx/conf.d/wordpress_01.conf
      # - ./nginx/conf.d/wordpress_02.conf:/etc/nginx/conf.d/wordpress_02.conf
      # - ./nginx/conf.d/static_01.conf:/etc/nginx/conf.d/static_01.conf
      - wordpress_01:/var/www/wordpress_01
      # - wordpress_02:/var/www/wordpress_02
      # - ../static_01:/var/www/static_01
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - sites

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - sites

secrets:
  db_root_password:
    file: secrets/db_root_password.txt

volumes:
  db:
  letsencrypt:
  wordpress_01:
  # wordpress_02:

networks:
  sites:
